/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BButton: typeof import('bootstrap-vue-next/components/BButton')['BButton']
    BCol: typeof import('bootstrap-vue-next/components/BContainer')['BCol']
    BCollapse: typeof import('bootstrap-vue-next/components/BCollapse')['BCollapse']
    BContainer: typeof import('bootstrap-vue-next/components/BContainer')['BContainer']
    BDropdownItem: typeof import('bootstrap-vue-next/components/BDropdown')['BDropdownItem']
    BFormGroup: typeof import('bootstrap-vue-next/components/BFormGroup')['BFormGroup']
    BFormInput: typeof import('bootstrap-vue-next/components/BFormInput')['BFormInput']
    BInputGroup: typeof import('bootstrap-vue-next/components/BInputGroup')['BInputGroup']
    BNavbar: typeof import('bootstrap-vue-next/components/BNavbar')['BNavbar']
    BNavbarBrand: typeof import('bootstrap-vue-next/components/BNavbar')['BNavbarBrand']
    BNavbarNav: typeof import('bootstrap-vue-next/components/BNavbar')['BNavbarNav']
    BNavbarToggle: typeof import('bootstrap-vue-next/components/BNavbar')['BNavbarToggle']
    BNavForm: typeof import('bootstrap-vue-next/components/BNav')['BNavForm']
    BNavItem: typeof import('bootstrap-vue-next/components/BNav')['BNavItem']
    BNavItemDropdown: typeof import('bootstrap-vue-next/components/BNav')['BNavItemDropdown']
    BRow: typeof import('bootstrap-vue-next/components/BContainer')['BRow']
    HeaderView: typeof import('./app/components/HeaderView.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
  export interface GlobalDirectives {
    vBColorMode: typeof import('bootstrap-vue-next/directives/BColorMode')['vBColorMode']
  }
}

// For TSX support
declare global {
  const BButton: typeof import('bootstrap-vue-next/components/BButton')['BButton']
  const BCol: typeof import('bootstrap-vue-next/components/BContainer')['BCol']
  const BCollapse: typeof import('bootstrap-vue-next/components/BCollapse')['BCollapse']
  const BContainer: typeof import('bootstrap-vue-next/components/BContainer')['BContainer']
  const BDropdownItem: typeof import('bootstrap-vue-next/components/BDropdown')['BDropdownItem']
  const BFormGroup: typeof import('bootstrap-vue-next/components/BFormGroup')['BFormGroup']
  const BFormInput: typeof import('bootstrap-vue-next/components/BFormInput')['BFormInput']
  const BInputGroup: typeof import('bootstrap-vue-next/components/BInputGroup')['BInputGroup']
  const BNavbar: typeof import('bootstrap-vue-next/components/BNavbar')['BNavbar']
  const BNavbarBrand: typeof import('bootstrap-vue-next/components/BNavbar')['BNavbarBrand']
  const BNavbarNav: typeof import('bootstrap-vue-next/components/BNavbar')['BNavbarNav']
  const BNavbarToggle: typeof import('bootstrap-vue-next/components/BNavbar')['BNavbarToggle']
  const BNavForm: typeof import('bootstrap-vue-next/components/BNav')['BNavForm']
  const BNavItem: typeof import('bootstrap-vue-next/components/BNav')['BNavItem']
  const BNavItemDropdown: typeof import('bootstrap-vue-next/components/BNav')['BNavItemDropdown']
  const BRow: typeof import('bootstrap-vue-next/components/BContainer')['BRow']
  const HeaderView: typeof import('./app/components/HeaderView.vue')['default']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
}