/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Anexosinput: typeof import('./../../app/components/inputs/anexosinput.vue')['default']
    BApp: typeof import('bootstrap-vue-next/components/BApp')['BApp']
    BBadge: typeof import('bootstrap-vue-next/components/BBadge')['BBadge']
    BButton: typeof import('bootstrap-vue-next/components/BButton')['BButton']
    BCol: typeof import('bootstrap-vue-next/components/BContainer')['BCol']
    BContainer: typeof import('bootstrap-vue-next/components/BContainer')['BContainer']
    BFormCheckbox: typeof import('bootstrap-vue-next/components/BFormCheckbox')['BFormCheckbox']
    BFormFile: typeof import('bootstrap-vue-next/components/BFormFile')['BFormFile']
    BFormFloatingLabel: typeof import('bootstrap-vue-next/components/BForm')['BFormFloatingLabel']
    BFormGroup: typeof import('bootstrap-vue-next/components/BFormGroup')['BFormGroup']
    BFormInput: typeof import('bootstrap-vue-next/components/BFormInput')['BFormInput']
    BFormSelect: typeof import('bootstrap-vue-next/components/BFormSelect')['BFormSelect']
    BInputGroup: typeof import('bootstrap-vue-next/components/BInputGroup')['BInputGroup']
    BListGroupItem: typeof import('bootstrap-vue-next/components/BListGroup')['BListGroupItem']
    BModal: typeof import('bootstrap-vue-next/components/BModal')['BModal']
    BNavbar: typeof import('bootstrap-vue-next/components/BNavbar')['BNavbar']
    BNavbarBrand: typeof import('bootstrap-vue-next/components/BNavbar')['BNavbarBrand']
    BNavbarNav: typeof import('bootstrap-vue-next/components/BNavbar')['BNavbarNav']
    BProgress: typeof import('bootstrap-vue-next/components/BProgress')['BProgress']
    BRow: typeof import('bootstrap-vue-next/components/BContainer')['BRow']
    BTooltip: typeof import('bootstrap-vue-next/components/BTooltip')['BTooltip']
    Crawjud: typeof import('./../../app/components/crawjud.vue')['default']
    CrawJUD: typeof import('./../../app/components/icons/CrawJUD.vue')['default']
    CrawJUDBrand: typeof import('./../../app/components/CrawJUDBrand.vue')['default']
    CredenciaisInput: typeof import('./../../app/components/inputs/credenciaisInput.vue')['default']
    Elaw: typeof import('./../../app/components/elaw.vue')['default']
    Esaj: typeof import('./../../app/components/esaj.vue')['default']
    InputPassword: typeof import('./../../app/components/inputs/InputPassword.vue')['default']
    Loading: typeof import('./../../app/components/loading.vue')['default']
    MessageArquivo: typeof import('./../../app/components/MessageArquivo.vue')['default']
    Navbar: typeof import('./../../app/components/navbar.vue')['default']
    Pje: typeof import('./../../app/components/pje.vue')['default']
    ProgressBar: typeof import('./../../app/components/ui/ProgressBar.vue')['default']
    Projudi: typeof import('./../../app/components/projudi.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./../../app/components/sidebar.vue')['default']
    Toast: typeof import('./../../app/components/toast.vue')['default']
    Xlsxinput: typeof import('./../../app/components/inputs/xlsxinput.vue')['default']
  }
}

// For TSX support
declare global {
  const Anexosinput: typeof import('./../../app/components/inputs/anexosinput.vue')['default']
  const BApp: typeof import('bootstrap-vue-next/components/BApp')['BApp']
  const BBadge: typeof import('bootstrap-vue-next/components/BBadge')['BBadge']
  const BButton: typeof import('bootstrap-vue-next/components/BButton')['BButton']
  const BCol: typeof import('bootstrap-vue-next/components/BContainer')['BCol']
  const BContainer: typeof import('bootstrap-vue-next/components/BContainer')['BContainer']
  const BFormCheckbox: typeof import('bootstrap-vue-next/components/BFormCheckbox')['BFormCheckbox']
  const BFormFile: typeof import('bootstrap-vue-next/components/BFormFile')['BFormFile']
  const BFormFloatingLabel: typeof import('bootstrap-vue-next/components/BForm')['BFormFloatingLabel']
  const BFormGroup: typeof import('bootstrap-vue-next/components/BFormGroup')['BFormGroup']
  const BFormInput: typeof import('bootstrap-vue-next/components/BFormInput')['BFormInput']
  const BFormSelect: typeof import('bootstrap-vue-next/components/BFormSelect')['BFormSelect']
  const BInputGroup: typeof import('bootstrap-vue-next/components/BInputGroup')['BInputGroup']
  const BListGroupItem: typeof import('bootstrap-vue-next/components/BListGroup')['BListGroupItem']
  const BModal: typeof import('bootstrap-vue-next/components/BModal')['BModal']
  const BNavbar: typeof import('bootstrap-vue-next/components/BNavbar')['BNavbar']
  const BNavbarBrand: typeof import('bootstrap-vue-next/components/BNavbar')['BNavbarBrand']
  const BNavbarNav: typeof import('bootstrap-vue-next/components/BNavbar')['BNavbarNav']
  const BProgress: typeof import('bootstrap-vue-next/components/BProgress')['BProgress']
  const BRow: typeof import('bootstrap-vue-next/components/BContainer')['BRow']
  const BTooltip: typeof import('bootstrap-vue-next/components/BTooltip')['BTooltip']
  const Crawjud: typeof import('./../../app/components/crawjud.vue')['default']
  const CrawJUD: typeof import('./../../app/components/icons/CrawJUD.vue')['default']
  const CrawJUDBrand: typeof import('./../../app/components/CrawJUDBrand.vue')['default']
  const CredenciaisInput: typeof import('./../../app/components/inputs/credenciaisInput.vue')['default']
  const Elaw: typeof import('./../../app/components/elaw.vue')['default']
  const Esaj: typeof import('./../../app/components/esaj.vue')['default']
  const InputPassword: typeof import('./../../app/components/inputs/InputPassword.vue')['default']
  const Loading: typeof import('./../../app/components/loading.vue')['default']
  const MessageArquivo: typeof import('./../../app/components/MessageArquivo.vue')['default']
  const Navbar: typeof import('./../../app/components/navbar.vue')['default']
  const Pje: typeof import('./../../app/components/pje.vue')['default']
  const ProgressBar: typeof import('./../../app/components/ui/ProgressBar.vue')['default']
  const Projudi: typeof import('./../../app/components/projudi.vue')['default']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
  const Sidebar: typeof import('./../../app/components/sidebar.vue')['default']
  const Toast: typeof import('./../../app/components/toast.vue')['default']
  const Xlsxinput: typeof import('./../../app/components/inputs/xlsxinput.vue')['default']
}