/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Anexos: typeof import('./../../app/components/bot/anexos.vue')['default']
    App: typeof import('./../../app/components/card/app.vue')['default']
    AppToast: typeof import('./../../app/components/AppToast.vue')['default']
    BApp: typeof import('bootstrap-vue-next/components/BApp')['BApp']
    BButton: typeof import('bootstrap-vue-next/components/BButton')['BButton']
    BContainer: typeof import('bootstrap-vue-next/components/BContainer')['BContainer']
    BFormGroup: typeof import('bootstrap-vue-next/components/BFormGroup')['BFormGroup']
    BFormInput: typeof import('bootstrap-vue-next/components/BFormInput')['BFormInput']
    BInputGroup: typeof import('bootstrap-vue-next/components/BInputGroup')['BInputGroup']
    BNavbar: typeof import('bootstrap-vue-next/components/BNavbar')['BNavbar']
    BNavbarBrand: typeof import('bootstrap-vue-next/components/BNavbar')['BNavbarBrand']
    BNavbarNav: typeof import('bootstrap-vue-next/components/BNavbar')['BNavbarNav']
    BTooltip: typeof import('bootstrap-vue-next/components/BTooltip')['BTooltip']
    Certificado: typeof import('./../../app/components/bot/certificado.vue')['default']
    Container: typeof import('./../../app/components/container.vue')['default']
    Crawjud: typeof import('./../../app/components/img/crawjud.vue')['default']
    Credencial: typeof import('./../../app/components/bot/credencial.vue')['default']
    DropFile: typeof import('./../../app/components/app/DropFile.vue')['default']
    Elaw: typeof import('./../../app/components/img/elaw.vue')['default']
    Empty: typeof import('./../../app/components/Empty.vue')['default']
    Esaj: typeof import('./../../app/components/img/esaj.vue')['default']
    Footer: typeof import('./../../app/components/ui/footer.vue')['default']
    Form: typeof import('./../../app/components/bot/Form.vue')['default']
    Header: typeof import('./../../app/components/ui/header.vue')['default']
    InputPassword: typeof import('./../../app/components/InputPassword.vue')['default']
    Kdbxfile: typeof import('./../../app/components/bot/kdbxfile.vue')['default']
    Loading: typeof import('./../../app/components/loading.vue')['default']
    MessageArquivo: typeof import('./../../app/components/MessageArquivo.vue')['default']
    Modal: typeof import('./../../app/components/app/Modal.vue')['default']
    Navbar: typeof import('./../../app/components/navbar.vue')['default']
    OtpInput: typeof import('./../../app/components/app/OtpInput.vue')['default']
    Pje: typeof import('./../../app/components/img/pje.vue')['default']
    Progress: typeof import('./../../app/components/bot/progress.vue')['default']
    Projudi: typeof import('./../../app/components/img/projudi.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./../../app/components/ui/sidebar.vue')['default']
    SimpleAuth: typeof import('./../../app/components/bot/simpleAuth.vue')['default']
    WindowExaple: typeof import('./../../app/components/WindowExaple.vue')['default']
    Xlsxfile: typeof import('./../../app/components/bot/xlsxfile.vue')['default']
  }
  export interface GlobalDirectives {
    vBColorMode: typeof import('bootstrap-vue-next/directives/BColorMode')['vBColorMode']
  }
}

// For TSX support
declare global {
  const Anexos: typeof import('./../../app/components/bot/anexos.vue')['default']
  const App: typeof import('./../../app/components/card/app.vue')['default']
  const AppToast: typeof import('./../../app/components/AppToast.vue')['default']
  const BApp: typeof import('bootstrap-vue-next/components/BApp')['BApp']
  const BButton: typeof import('bootstrap-vue-next/components/BButton')['BButton']
  const BContainer: typeof import('bootstrap-vue-next/components/BContainer')['BContainer']
  const BFormGroup: typeof import('bootstrap-vue-next/components/BFormGroup')['BFormGroup']
  const BFormInput: typeof import('bootstrap-vue-next/components/BFormInput')['BFormInput']
  const BInputGroup: typeof import('bootstrap-vue-next/components/BInputGroup')['BInputGroup']
  const BNavbar: typeof import('bootstrap-vue-next/components/BNavbar')['BNavbar']
  const BNavbarBrand: typeof import('bootstrap-vue-next/components/BNavbar')['BNavbarBrand']
  const BNavbarNav: typeof import('bootstrap-vue-next/components/BNavbar')['BNavbarNav']
  const BTooltip: typeof import('bootstrap-vue-next/components/BTooltip')['BTooltip']
  const Certificado: typeof import('./../../app/components/bot/certificado.vue')['default']
  const Container: typeof import('./../../app/components/container.vue')['default']
  const Crawjud: typeof import('./../../app/components/img/crawjud.vue')['default']
  const Credencial: typeof import('./../../app/components/bot/credencial.vue')['default']
  const DropFile: typeof import('./../../app/components/app/DropFile.vue')['default']
  const Elaw: typeof import('./../../app/components/img/elaw.vue')['default']
  const Empty: typeof import('./../../app/components/Empty.vue')['default']
  const Esaj: typeof import('./../../app/components/img/esaj.vue')['default']
  const Footer: typeof import('./../../app/components/ui/footer.vue')['default']
  const Form: typeof import('./../../app/components/bot/Form.vue')['default']
  const Header: typeof import('./../../app/components/ui/header.vue')['default']
  const InputPassword: typeof import('./../../app/components/InputPassword.vue')['default']
  const Kdbxfile: typeof import('./../../app/components/bot/kdbxfile.vue')['default']
  const Loading: typeof import('./../../app/components/loading.vue')['default']
  const MessageArquivo: typeof import('./../../app/components/MessageArquivo.vue')['default']
  const Modal: typeof import('./../../app/components/app/Modal.vue')['default']
  const Navbar: typeof import('./../../app/components/navbar.vue')['default']
  const OtpInput: typeof import('./../../app/components/app/OtpInput.vue')['default']
  const Pje: typeof import('./../../app/components/img/pje.vue')['default']
  const Progress: typeof import('./../../app/components/bot/progress.vue')['default']
  const Projudi: typeof import('./../../app/components/img/projudi.vue')['default']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
  const Sidebar: typeof import('./../../app/components/ui/sidebar.vue')['default']
  const SimpleAuth: typeof import('./../../app/components/bot/simpleAuth.vue')['default']
  const WindowExaple: typeof import('./../../app/components/WindowExaple.vue')['default']
  const Xlsxfile: typeof import('./../../app/components/bot/xlsxfile.vue')['default']
}